Progressao/urls.py
from django.contrib import admin
# adicionar o include para importar urls dos apps
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Importa todas as urls criadas no app páginas
    path('', include('paginas.urls') ),
    path('', include('cadastros.urls')),
    path('', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cadastros/urls.py
from django.urls import path

# Importa as views que a gente criou
from .views import StatusCreate, SituacaoCreate, ClasseCreate
from .views import ServidorUpdate, StatusUpdate, SituacaoUpdate, ClasseUpdate
from .views import StatusDelete, SituacaoDelete, ClasseDelete
from .views import  StatusList, SituacaoList, ClasseList, FrequenciaList, LancarFreqList

# Tem que ser urlpatterns porque é padrão do Django
urlpatterns = [

    path('cadastrar/status/', StatusCreate.as_view(), name="cadastrar-status"),
    path('cadastrar/situacao/', SituacaoCreate.as_view(), name="cadastrar-situacao"),
    path('cadastrar/classe/', ClasseCreate.as_view(), name="cadastrar-classe"),




    path('editar/status/<int:pk>/', StatusUpdate.as_view(), name="editar-status"),
    path('editar/situacao/<int:pk>/', SituacaoUpdate.as_view(), name="editar-situacao"),
    path('editar/classe/<int:pk>/', ClasseUpdate.as_view(), name="editar-classe"),



    path('excluir/status/<int:pk>/', StatusDelete.as_view(), name="excluir-status"),
    path('excluir/situacao/<int:pk>/', SituacaoDelete.as_view(), name="excluir-situacao"),
    path('excluir/classe/<int:pk>/', ClasseDelete.as_view(), name="excluir-classe"),



    path('listar/status/', StatusList.as_view(), name="listar-status"),
    path('listar/situacoes/', SituacaoList.as_view(), name="listar-situacao"),
    path('listar/classes/', ClasseList.as_view(), name="listar-classe"),
    path('listar/frequencia/', FrequenciaList.as_view(), name="listar-frequencia"),
    path('listar/lancar_freq_6a/', LancarFreqList.as_view(), name="listar-lancar_freq_6a"),


]

paginas/urls.py
from django.urls import path

# Importa as views que a gente criou 
from .views import PaginaInicial, SobreView

# Tem que ser urlpatterns porque é padrão do Django
urlpatterns = [
    # Todo path tem endereço, sua_view.as_view() e nome
    path('', PaginaInicial.as_view(), name='index'),
    path('sobre/', SobreView.as_view(), name='sobre'),
]

cadastros/models.py
from django.db import models
from django.contrib.auth.models import User

# Métodos e Choices


def user_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'usuario_{0}/{1}'.format(instance.user.id, filename)


# Classes (modelos)



class Servidor(models.Model):
    nome_completo = models.CharField(max_length=100)
    siape = models.CharField(max_length=10)
    cpf = models.CharField(max_length=14, verbose_name="CPF")
    usuario = models.ForeignKey(
        User, on_delete=models.PROTECT, verbose_name="usuário")


class Status(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=150, verbose_name="descrição")

    def __str__(self):
        return "{} ({})".format(self.nome, self.descricao)


class Situacao(models.Model):
    status = models.ForeignKey(Status, on_delete=models.PROTECT)
    detalhes = models.CharField(max_length=255, blank=True, null=True)


class Classe(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.CharField(max_length=150, verbose_name="descrição", null=True, blank=True)

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Perfil(models.Model):
    nome_completo = models.CharField(max_length=50, null=True)
    cpf = models.CharField(max_length=14, null=True, verbose_name="CPF")
    telefone = models.CharField(max_length=16, null=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

cadastros/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .models import Servidor, Status, Situacao, Classe

from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import GroupRequiredMixin

from django.shortcuts import get_object_or_404

# Create your views here.





class StatusCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Status
    fields = ['nome', 'descricao']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-status')


class SituacaoCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Situacao
    fields = ['status', 'detalhes']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-situacao')


class ClasseCreate(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    model = Classe
    fields = ['nome', 'descricao']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-classe')









class ServidorUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Servidor
    fields = ['nome_completo', 'siape', 'cpf', 'campus']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('index')


class StatusUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Status
    fields = ['nome', 'descricao']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-status')


class SituacaoUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Situacao
    fields = ['status', 'detalhes']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-situacao')


class ClasseUpdate(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    model = Classe
    fields = ['nome', 'descricao']
    template_name = 'cadastros/form.html'
    success_url = reverse_lazy('listar-classe')





class StatusDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Status
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-status')


class SituacaoDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Situacao
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-situacao')


class ClasseDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    model = Classe
    template_name = 'cadastros/form-excluir.html'
    success_url = reverse_lazy('listar-classe')















################# LISTA #################




class StatusList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Status
    template_name = 'cadastros/listas/status.html'


class SituacaoList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Situacao
    template_name = 'cadastros/listas/situacao.html'


class ClasseList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Classe
    template_name = 'cadastros/listas/classe.html'

class FrequenciaList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Classe
    template_name = 'cadastros/listas/frequencia.html'

class LancarFreqList(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    model = Classe
    template_name = 'cadastros/listas/lancar_freq_6a.html'

cadastros/templates/cadastros/form-excluir.html
{% extends 'paginas/modelo-ifpr.html' %}

{% load static %}

{% block conteudo %}
<h3>Excluir registros</h3>

<p class="lead">
    Confirme para exlcuir o registro definitivamente.
</p>

<hr>

<form action="" method="POST">

    <p>
        Deseja excluir o registro: <strong>{{ object }}</strong>?
    </p>

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" class="btn btn-danger">Excluir</button>

</form>

{% endblock %}

cadastros/templates/cadastros/form-upload.html
{% extends 'paginas/modelo-ifpr.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<h3>{{ titulo }}</h3>

<p class="lead">
    Preencha todos os campos obrigatórios.
</p>

<hr>

<form action="" method="POST" enctype="multipart/form-data">

    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-light mt-3">
        {% autoescape off %}
        {{ icone }}
        {% endautoescape %}
        {{ botao }}
    </button>

</form>

{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        // $("input:enabled:visible:first").focus();

        // $("input[name*=data]").attr("type", "date");
    });
</script>
{% endblock %}

cadastros/templates/cadastros/form.html
{% extends 'paginas/modelo-ifpr.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block conteudo %}
<h3>{{ titulo }}</h3>

<p class="lead">
    Preencha todos os campos obrigatórios.
</p>

<hr>

<form action="" method="POST">

    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-light mt-3">
        {% autoescape off %}
        {{ icone }}
        {% endautoescape %}
        {{ botao }}
    </button>

</form>

{% endblock %}

{% block scripts %}
<script src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function(){

        $("#id_cpf").mask("000.000.000-00");
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 0 0000-0000' : '(00) 0000-00009';
        },
            spOptions = {
                onKeyPress: function (val, e, field, options) {
                    field.mask(SPMaskBehavior.apply({}, arguments), options);
                }
            };

        $('#id_telefone').mask(SPMaskBehavior, spOptions);


    });
</script>
{% endblock %}